{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading data...\n",
      "(50000, 500, 1)\n",
      "(50000,)\n",
      "(31000, 500, 1)"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING (theano.sandbox.cuda.opt): Optimization Warning: Got the following error, but you can ignore it. This could cause less GpuElemwise fused together.\n",
      "error copying data to from memory\n",
      "WARNING:theano.sandbox.cuda.opt:Optimization Warning: Got the following error, but you can ignore it. This could cause less GpuElemwise fused together.\n",
      "error copying data to from memory\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of 1e-06})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of 1e-06})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of 0.0})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of 0.0})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of inf})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of inf})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of 1e-06})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of 1e-06})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of 0.0})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of 0.0})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of inf})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of inf})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1,) of 1e-06})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1,) of 1e-06})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1,) of 0.0})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1,) of 0.0})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1,) of inf})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1,) of inf})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of 1e-06})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of 1e-06})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of 0.0})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of 0.0})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of inf})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of inf})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of 1e-06})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of 1e-06})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of 0.0})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of 0.0})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of inf})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of inf})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1,) of 1e-06})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1,) of 1e-06})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1,) of 0.0})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1,) of 0.0})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1,) of inf})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1,) of inf})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of 1e-06})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of 1e-06})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of 0.0})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of 0.0})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of inf})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of inf})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of 1e-06})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of 1e-06})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of 0.0})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of 0.0})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of inf})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of inf})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1,) of 1e-06})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1,) of 1e-06})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1,) of 0.0})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1,) of 0.0})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1,) of inf})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1,) of inf})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR:theano.gof.opt:Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: constant_folding\n",
      "ERROR:theano.gof.opt:Optimization failure due to: constant_folding\n",
      "ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1) of 1e-06})\n",
      "ERROR:theano.gof.opt:node: GpuFromHost(TensorConstant{(1, 1) of 1e-06})\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR:theano.gof.opt:TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/opt.py\", line 1772, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py\", line 5802, in constant_folding\n",
      "    required = thunk()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/op.py\", line 883, in rval\n",
      "    fill_storage()\n",
      "  File \"/Users/rahul/anaconda/lib/python2.7/site-packages/theano/gof/cc.py\", line 1707, in __call__\n",
      "    reraise(exc_type, exc_value, exc_trace)\n",
      "  File \"<string>\", line 2, in reraise\n",
      "MemoryError: Error allocating 4 bytes of device memory (unspecified launch failure).\n",
      "\n"
     ]
    }
   ],
   "source": [
    "from __future__ import print_function\n",
    "import numpy as np\n",
    "from numpy import newaxis\n",
    "import pandas as pd\n",
    "from keras.preprocessing import sequence\n",
    "from keras.models import Sequential\n",
    "from keras.layers.core import Dense, Dropout, Activation, Flatten\n",
    "from keras.optimizers import SGD\n",
    "from keras.layers.convolutional import Convolution1D, MaxPooling1D, ZeroPadding1D\n",
    "from keras.layers.recurrent import LSTM, GRU, SimpleRNN\n",
    "\n",
    "\n",
    "# set parameters:\n",
    "batch_size = 16\n",
    "input_dim = 1\n",
    "nb_epoch = 10\n",
    "\n",
    "print('Loading data...')\n",
    "file1 = \"training.txt\"\n",
    "file2 = \"testing.txt\"\n",
    "\n",
    "# data loading\n",
    "data1 = np.loadtxt(file1, delimiter=',')\n",
    "X_train = data1[:50000, :500, newaxis]\n",
    "print(X_train.shape)\n",
    "\n",
    "y_train = data1[:50000, -1]\n",
    "print(y_train.shape)\n",
    "\n",
    "data2 = np.loadtxt(file2, delimiter=',')\n",
    "X_test = data2[:, :500, newaxis]\n",
    "print(X_test.shape)\n",
    "\n",
    "\n",
    "y_test = data2[:, -1]\n",
    "print(y_test.shape)\n",
    "\n",
    "print('Build model...')\n",
    "model = Sequential()\n",
    "\n",
    "model.add(GRU(output_dim=64, input_dim=input_dim))\n",
    "model.add(Dropout(0.25))\n",
    "model.add(Activation('relu'))\n",
    "#two FC layers\n",
    "model.add(Dense(128))\n",
    "model.add(Activation('relu'))\n",
    "model.add(Dropout(0.25))\n",
    "model.add(Dense(128))\n",
    "model.add(Dropout(0.25))\n",
    "model.add(Activation('relu'))\n",
    "\n",
    "# We project onto a single unit output layer, and squash it with a sigmoid:\n",
    "model.add(Dense(1)) \n",
    "model.add(Activation('sigmoid'))\n",
    "\n",
    "model.compile(loss='binary_crossentropy',\n",
    "              optimizer='rmsprop',\n",
    "              class_mode='binary')\n",
    "\n",
    "print('Train...')\n",
    "model.fit(X_train, y_train, batch_size=batch_size,\n",
    "          nb_epoch=nb_epoch, show_accuracy=True,\n",
    "          validation_data=(X_test, y_test))\n",
    "score, acc = model.evaluate(X_test, y_test, batch_size=batch_size,\n",
    "                            show_accuracy=True)\n",
    "print('Test score:', score)\n",
    "print('Test accuracy:', acc)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
